"""add recipe table

Revision ID: 45a23269becb
Revises: 9dbded0aa146
Create Date: 2026-06-07 17:14:10.505020
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel  # noqa: F401  (SQLModel emits sqlmodel.sql.sqltypes in autogenerate)
from alembic import op

from sqlalchemy.dialects import postgresql

revision: str = '45a23269becb'
down_revision: str | None = '9dbded0aa146'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipe',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('owner_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('workspace_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tags', sa.ARRAY(sa.String()), server_default='{}', nullable=False),
    sa.Column('mode', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('config_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recipe_mode'), 'recipe', ['mode'], unique=False)
    op.create_index(op.f('ix_recipe_name'), 'recipe', ['name'], unique=False)
    op.create_index(op.f('ix_recipe_owner_id'), 'recipe', ['owner_id'], unique=False)
    op.create_index(op.f('ix_recipe_workspace_id'), 'recipe', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recipe_workspace_id'), table_name='recipe')
    op.drop_index(op.f('ix_recipe_owner_id'), table_name='recipe')
    op.drop_index(op.f('ix_recipe_name'), table_name='recipe')
    op.drop_index(op.f('ix_recipe_mode'), table_name='recipe')
    op.drop_table('recipe')
    # ### end Alembic commands ###
