"""initial schema

Revision ID: 9dbded0aa146
Revises: 
Create Date: 2026-06-07 16:15:23.432879
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel  # noqa: F401  (SQLModel emits sqlmodel.sql.sqltypes in autogenerate)
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '9dbded0aa146'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('owner_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('workspace_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('scope', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_job_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('storage_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('thumb_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tags', sa.ARRAY(sa.String()), server_default='{}', nullable=False),
    sa.Column('collection', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('format', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('bytes', sa.Integer(), nullable=False),
    sa.Column('sha256', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_collection'), 'asset', ['collection'], unique=False)
    op.create_index(op.f('ix_asset_owner_id'), 'asset', ['owner_id'], unique=False)
    op.create_index(op.f('ix_asset_scope'), 'asset', ['scope'], unique=False)
    op.create_index(op.f('ix_asset_sha256'), 'asset', ['sha256'], unique=False)
    op.create_index(op.f('ix_asset_source'), 'asset', ['source'], unique=False)
    op.create_index(op.f('ix_asset_source_job_id'), 'asset', ['source_job_id'], unique=False)
    op.create_index(op.f('ix_asset_workspace_id'), 'asset', ['workspace_id'], unique=False)
    op.create_table('integration',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('owner_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('workspace_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('encrypted_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_validated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_integration_owner_id'), 'integration', ['owner_id'], unique=False)
    op.create_index(op.f('ix_integration_provider'), 'integration', ['provider'], unique=False)
    op.create_index(op.f('ix_integration_workspace_id'), 'integration', ['workspace_id'], unique=False)
    op.create_table('job',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('owner_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('workspace_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('batch_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('mode', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('precision', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('device', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('model_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('model_revision', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('prompt', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('enhanced_prompt', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('rewriter_model', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('params_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('progress_step', sa.Integer(), nullable=False),
    sa.Column('progress_total', sa.Integer(), nullable=False),
    sa.Column('error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_batch_id'), 'job', ['batch_id'], unique=False)
    op.create_index(op.f('ix_job_mode'), 'job', ['mode'], unique=False)
    op.create_index(op.f('ix_job_owner_id'), 'job', ['owner_id'], unique=False)
    op.create_index(op.f('ix_job_status'), 'job', ['status'], unique=False)
    op.create_index(op.f('ix_job_workspace_id'), 'job', ['workspace_id'], unique=False)
    op.create_table('lora',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('owner_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('workspace_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('storage_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('thumb_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('trigger_words', sa.ARRAY(sa.String()), server_default='{}', nullable=False),
    sa.Column('recommended_weight', sa.Float(), nullable=False),
    sa.Column('base_compat', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('modes', sa.ARRAY(sa.String()), server_default='{}', nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_ref', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('license', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sha256', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('bytes', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lora_base_compat'), 'lora', ['base_compat'], unique=False)
    op.create_index(op.f('ix_lora_name'), 'lora', ['name'], unique=False)
    op.create_index(op.f('ix_lora_owner_id'), 'lora', ['owner_id'], unique=False)
    op.create_index(op.f('ix_lora_sha256'), 'lora', ['sha256'], unique=False)
    op.create_index(op.f('ix_lora_workspace_id'), 'lora', ['workspace_id'], unique=False)
    op.create_table('prompt',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('owner_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('workspace_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tags', sa.ARRAY(sa.String()), server_default='{}', nullable=False),
    sa.Column('mode', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('favorite', sa.Boolean(), nullable=False),
    sa.Column('defaults_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prompt_mode'), 'prompt', ['mode'], unique=False)
    op.create_index(op.f('ix_prompt_name'), 'prompt', ['name'], unique=False)
    op.create_index(op.f('ix_prompt_owner_id'), 'prompt', ['owner_id'], unique=False)
    op.create_index(op.f('ix_prompt_workspace_id'), 'prompt', ['workspace_id'], unique=False)
    op.create_table('setting',
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('job_input',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('job_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('asset_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sha256', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_input_job_id'), 'job_input', ['job_id'], unique=False)
    op.create_table('job_output',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('job_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('storage_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('thumb_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('seed', sa.Integer(), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_output_job_id'), 'job_output', ['job_id'], unique=False)
    op.create_table('prompt_image',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('prompt_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('asset_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('slot_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('slot_min', sa.Integer(), nullable=True),
    sa.Column('slot_max', sa.Integer(), nullable=True),
    sa.Column('hint', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ),
    sa.ForeignKeyConstraint(['prompt_id'], ['prompt.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prompt_image_prompt_id'), 'prompt_image', ['prompt_id'], unique=False)
    op.create_table('prompt_lora',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('prompt_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('lora_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['lora_id'], ['lora.id'], ),
    sa.ForeignKeyConstraint(['prompt_id'], ['prompt.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prompt_lora_prompt_id'), 'prompt_lora', ['prompt_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prompt_lora_prompt_id'), table_name='prompt_lora')
    op.drop_table('prompt_lora')
    op.drop_index(op.f('ix_prompt_image_prompt_id'), table_name='prompt_image')
    op.drop_table('prompt_image')
    op.drop_index(op.f('ix_job_output_job_id'), table_name='job_output')
    op.drop_table('job_output')
    op.drop_index(op.f('ix_job_input_job_id'), table_name='job_input')
    op.drop_table('job_input')
    op.drop_table('setting')
    op.drop_index(op.f('ix_prompt_workspace_id'), table_name='prompt')
    op.drop_index(op.f('ix_prompt_owner_id'), table_name='prompt')
    op.drop_index(op.f('ix_prompt_name'), table_name='prompt')
    op.drop_index(op.f('ix_prompt_mode'), table_name='prompt')
    op.drop_table('prompt')
    op.drop_index(op.f('ix_lora_workspace_id'), table_name='lora')
    op.drop_index(op.f('ix_lora_sha256'), table_name='lora')
    op.drop_index(op.f('ix_lora_owner_id'), table_name='lora')
    op.drop_index(op.f('ix_lora_name'), table_name='lora')
    op.drop_index(op.f('ix_lora_base_compat'), table_name='lora')
    op.drop_table('lora')
    op.drop_index(op.f('ix_job_workspace_id'), table_name='job')
    op.drop_index(op.f('ix_job_status'), table_name='job')
    op.drop_index(op.f('ix_job_owner_id'), table_name='job')
    op.drop_index(op.f('ix_job_mode'), table_name='job')
    op.drop_index(op.f('ix_job_batch_id'), table_name='job')
    op.drop_table('job')
    op.drop_index(op.f('ix_integration_workspace_id'), table_name='integration')
    op.drop_index(op.f('ix_integration_provider'), table_name='integration')
    op.drop_index(op.f('ix_integration_owner_id'), table_name='integration')
    op.drop_table('integration')
    op.drop_index(op.f('ix_asset_workspace_id'), table_name='asset')
    op.drop_index(op.f('ix_asset_source_job_id'), table_name='asset')
    op.drop_index(op.f('ix_asset_source'), table_name='asset')
    op.drop_index(op.f('ix_asset_sha256'), table_name='asset')
    op.drop_index(op.f('ix_asset_scope'), table_name='asset')
    op.drop_index(op.f('ix_asset_owner_id'), table_name='asset')
    op.drop_index(op.f('ix_asset_collection'), table_name='asset')
    op.drop_table('asset')
    # ### end Alembic commands ###
