"""add job_output.asset_id

Revision ID: fe1a4a02e435
Revises: 45a23269becb
Create Date: 2026-06-08 03:37:24.844244
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel  # noqa: F401  (SQLModel emits sqlmodel.sql.sqltypes in autogenerate)
from alembic import op



revision: str = 'fe1a4a02e435'
down_revision: str | None = '45a23269becb'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_output', sa.Column('asset_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_foreign_key(None, 'job_output', 'asset', ['asset_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'job_output', type_='foreignkey')
    op.drop_column('job_output', 'asset_id')
    # ### end Alembic commands ###
