import { useEffect, useRef, useState } from "react";
import {
  Upload,
  Search,
  Star,
  Trash2,
  ArrowRightToLine,
  Images as ImagesIcon,
  Pencil,
  Tag,
} from "lucide-react";
import { PageHeader } from "@/components/PageHeader";
import { EmptyState } from "@/components/EmptyState";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Badge } from "@/components/ui/badge";
import { Skeleton } from "@/components/ui/skeleton";
import { Tabs, TabsList, TabsTrigger } from "@/components/ui/tabs";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogFooter,
} from "@/components/ui/dialog";
import {
  useAssets,
  useUploadAssets,
  usePromoteAsset,
  useDeleteAsset,
  usePatchAsset,
} from "@/api/hooks";
import { assetThumbUrl, assetFileUrl } from "@/api/client";
import { useComposer, newUid } from "@/store/composer";
import { useNavigate } from "react-router-dom";
import { formatBytes } from "@/lib/utils";
import { toast } from "sonner";
import type { Asset } from "@/api/types";

/** A friendly label for an asset: its name, unless that's an auto-generated id-like string. */
function displayName(a: Asset): string {
  const name = (a.name ?? "").trim();
  // Promoted generation outputs are named "<job-uuid>-<n>"; that reads as a UUID.
  const looksAutogenerated =
    !name || /^[0-9a-f-]{8,}(-\d+)?$/i.test(name) || name === a.id;
  return looksAutogenerated ? "Untitled" : name;
}

function EditAssetDialog({
  asset,
  onClose,
}: {
  asset: Asset | null;
  onClose: () => void;
}) {
  const patch = usePatchAsset();
  const [name, setName] = useState("");
  const [tags, setTags] = useState("");
  const [description, setDescription] = useState("");

  useEffect(() => {
    if (asset) {
      setName(asset.name ?? "");
      setTags((asset.tags ?? []).join(", "));
      setDescription(asset.description ?? "");
    }
  }, [asset]);

  const save = () => {
    if (!asset) return;
    const tagList = tags
      .split(",")
      .map((t) => t.trim())
      .filter(Boolean);
    patch
      .mutateAsync({
        id: asset.id,
        body: { name: name.trim(), tags: tagList, description: description.trim() },
      })
      .then(() => {
        toast.success("Saved");
        onClose();
      })
      .catch((e) => toast.error((e as Error).message));
  };

  return (
    <Dialog open={!!asset} onOpenChange={(o) => !o && onClose()}>
      <DialogContent>
        <DialogHeader>
          <DialogTitle>Edit image details</DialogTitle>
        </DialogHeader>
        {asset && (
          <div className="flex gap-4">
            <img
              src={assetThumbUrl(asset.id, asset.thumb_key) ?? assetFileUrl(asset.id)}
              alt={displayName(asset)}
              className="h-28 w-28 shrink-0 rounded-xl border object-cover"
            />
            <div className="min-w-0 flex-1 space-y-3">
              <div className="space-y-1.5">
                <Label htmlFor="asset-name">Title</Label>
                <Input
                  id="asset-name"
                  placeholder="A descriptive name…"
                  value={name}
                  onChange={(e) => setName(e.target.value)}
                />
              </div>
              <div className="space-y-1.5">
                <Label htmlFor="asset-tags">Tags</Label>
                <Input
                  id="asset-tags"
                  placeholder="comma, separated, tags"
                  value={tags}
                  onChange={(e) => setTags(e.target.value)}
                />
                <p className="text-[11px] text-muted-foreground">
                  Searchable. Separate with commas.
                </p>
              </div>
              <div className="space-y-1.5">
                <Label htmlFor="asset-desc">Description</Label>
                <Textarea
                  id="asset-desc"
                  rows={2}
                  placeholder="Optional notes…"
                  value={description}
                  onChange={(e) => setDescription(e.target.value)}
                />
              </div>
            </div>
          </div>
        )}
        <DialogFooter>
          <Button variant="ghost" onClick={onClose}>
            Cancel
          </Button>
          <Button onClick={save} disabled={patch.isPending}>
            {patch.isPending ? "Saving…" : "Save"}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}

export function ImagesPage() {
  const [scope, setScope] = useState<"library" | "ephemeral">("library");
  const [q, setQ] = useState("");
  const { data, isLoading } = useAssets({ scope, q });
  const upload = useUploadAssets();
  const promote = usePromoteAsset();
  const remove = useDeleteAsset();
  const fileRef = useRef<HTMLInputElement>(null);
  const navigate = useNavigate();
  const addInputs = useComposer((s) => s.addInputs);
  const [editing, setEditing] = useState<Asset | null>(null);

  const sendToComposer = (a: Asset) => {
    useComposer.getState().setMode("edit");
    addInputs([{ uid: newUid(), asset: a, origin: "library" }]);
    navigate("/compose");
    toast.success("Added to composer");
  };

  return (
    <div className="space-y-5 p-6">
      <PageHeader
        title="Images"
        description="Persistent library assets and ephemeral uploads. Promote either into the library."
        actions={
          <Button onClick={() => fileRef.current?.click()}>
            <Upload className="h-4 w-4" /> Upload
          </Button>
        }
      />
      <input
        ref={fileRef}
        type="file"
        accept="image/*,.heic,.heif"
        multiple
        hidden
        onChange={(e) =>
          e.target.files &&
          upload
            .mutateAsync(Array.from(e.target.files))
            .then(() => toast.success("Uploaded"))
            .catch((err) => toast.error((err as Error).message))
        }
      />

      <div className="flex items-center gap-3">
        <Tabs value={scope} onValueChange={(v) => setScope(v as typeof scope)}>
          <TabsList>
            <TabsTrigger value="library">Library</TabsTrigger>
            <TabsTrigger value="ephemeral">Uploads</TabsTrigger>
          </TabsList>
        </Tabs>
        <div className="relative flex-1 max-w-sm">
          <Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" />
          <Input
            className="pl-9"
            placeholder="Search by name or tag…"
            value={q}
            onChange={(e) => setQ(e.target.value)}
          />
        </div>
      </div>

      {isLoading ? (
        <div className="grid grid-cols-2 gap-4 sm:grid-cols-3 lg:grid-cols-5">
          {Array.from({ length: 10 }).map((_, i) => (
            <Skeleton key={i} className="aspect-square" />
          ))}
        </div>
      ) : !data?.length ? (
        <EmptyState
          icon={ImagesIcon}
          title="No images yet"
          description="Upload images or generate outputs and promote them here."
          action={
            <Button onClick={() => fileRef.current?.click()}>
              <Upload className="h-4 w-4" /> Upload
            </Button>
          }
        />
      ) : (
        <div className="grid grid-cols-2 gap-4 sm:grid-cols-3 lg:grid-cols-5">
          {data.map((a) => (
            <div
              key={a.id}
              className="group relative overflow-hidden rounded-2xl border bg-card elevated"
            >
              <img
                src={assetThumbUrl(a.id, a.thumb_key) ?? assetFileUrl(a.id)}
                alt={displayName(a)}
                className="aspect-square w-full object-cover"
              />
              <div className="p-2">
                <div className="truncate text-sm font-medium" title={a.name || undefined}>
                  {displayName(a)}
                </div>
                <div className="flex items-center gap-1.5 text-[11px] text-muted-foreground">
                  <span>{a.width}×{a.height}</span>
                  <span>·</span>
                  <span>{formatBytes(a.bytes)}</span>
                  <Badge variant="muted" className="ml-auto text-[10px]">
                    {a.source}
                  </Badge>
                </div>
                {a.tags.length > 0 && (
                  <div className="mt-1.5 flex flex-wrap gap-1">
                    {a.tags.slice(0, 4).map((t) => (
                      <Badge key={t} variant="outline" className="gap-0.5 text-[10px]">
                        <Tag className="h-2.5 w-2.5" /> {t}
                      </Badge>
                    ))}
                    {a.tags.length > 4 && (
                      <Badge variant="outline" className="text-[10px]">
                        +{a.tags.length - 4}
                      </Badge>
                    )}
                  </div>
                )}
              </div>
              <div className="absolute inset-x-0 top-0 flex justify-end gap-1 p-2 opacity-0 transition-opacity group-hover:opacity-100">
                <Button
                  size="icon"
                  variant="secondary"
                  className="h-7 w-7"
                  title="Edit title & tags"
                  onClick={() => setEditing(a)}
                >
                  <Pencil className="h-3.5 w-3.5" />
                </Button>
                <Button
                  size="icon"
                  variant="secondary"
                  className="h-7 w-7"
                  title="Send to composer"
                  onClick={() => sendToComposer(a)}
                >
                  <ArrowRightToLine className="h-3.5 w-3.5" />
                </Button>
                {a.scope === "ephemeral" && (
                  <Button
                    size="icon"
                    variant="secondary"
                    className="h-7 w-7"
                    title="Promote to library"
                    onClick={() =>
                      promote
                        .mutateAsync(a.id)
                        .then(() => toast.success("Promoted"))
                        .catch((e) => toast.error((e as Error).message))
                    }
                  >
                    <Star className="h-3.5 w-3.5" />
                  </Button>
                )}
                <Button
                  size="icon"
                  variant="secondary"
                  className="h-7 w-7"
                  title="Delete"
                  onClick={() =>
                    remove
                      .mutateAsync(a.id)
                      .then(() => toast.success("Deleted"))
                      .catch((e) => toast.error((e as Error).message))
                  }
                >
                  <Trash2 className="h-3.5 w-3.5" />
                </Button>
              </div>
            </div>
          ))}
        </div>
      )}

      <EditAssetDialog asset={editing} onClose={() => setEditing(null)} />
    </div>
  );
}
